spring.application.name=Suyog_ZorvynAssignment

# Database configuration (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:financetracker
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA and Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (available at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Security
spring.security.user.name=admin
spring.security.user.password=admin
